# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  hc10_joint_1_s:
    has_velocity_limits: true
    max_velocity: 2.2689
    has_acceleration_limits: false
    max_acceleration: 0
  hc10_joint_2_l:
    has_velocity_limits: true
    max_velocity: 2.2689
    has_acceleration_limits: false
    max_acceleration: 0
  hc10_joint_3_u:
    has_velocity_limits: true
    max_velocity: 3.1415
    has_acceleration_limits: false
    max_acceleration: 0
  hc10_joint_4_r:
    has_velocity_limits: true
    max_velocity: 3.1415
    has_acceleration_limits: false
    max_acceleration: 0
  hc10_joint_5_b:
    has_velocity_limits: true
    max_velocity: 4.36333
    has_acceleration_limits: false
    max_acceleration: 0
  hc10_joint_6_t:
    has_velocity_limits: true
    max_velocity: 4.36333
    has_acceleration_limits: false
    max_acceleration: 0